CREATE DATABASE QLNS


CREATE TABLE NHANVIEN
(
	MANV int NOT NULL PRIMARY KEY identity,
	TENNV NVARCHAR(60),
	AVATAR NVARCHAR(200)  DEFAULT 'Anonymous.png',
	NGAYVAOLAM DATETIME,
	GIOITINH BIT NOT NULL,
	PHONGBAN NVARCHAR(60) NOT NULL,
	LOAICONGVIEC NVARCHAR(60) NOT NULL,
)

CREATE TABLE LUONG
(
	MALUONG int NOT NULL PRIMARY KEY identity,
	LUONGCOBAN FLOAT DEFAULT 0,
	HESOLUONG FLOAT DEFAULT 0,
	LUONG1GIO FLOAT DEFAULT 0,
	LUONG1NGAY FLOAT DEFAULT 0,
	SONGAYLAM INT DEFAULT 0,
	SOGIOLAM INT DEFAULT 0,
	LUONGTHUONG INT DEFAULT 0,
	THANHLUONG FLOAT DEFAULT 0,
	MANV int NOT NULL
)

CREATE TABLE [USER]
(
	IDUSER int NOT NULL PRIMARY KEY identity,
	FULLNAME NVARCHAR(200),
	AVATAR NVARCHAR(200) DEFAULT 'Anonymous.png',
	USERNAME NVARCHAR(200) NOT NULL UNIQUE,
	[PASSWORD] NVARCHAR(200) NOT NULL
)

CREATE TABLE [ROLE]
(
	IDROLE int NOT NULL PRIMARY KEY identity,
	USERNAME NVARCHAR(200) NOT NULL,
	ROLECODE NVARCHAR(200) NOT NULL,
)

ALTER TABLE LUONG
ADD CONSTRAINT FK_LUONG_MANV_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [ROLE]
ADD CONSTRAINT FK_ROLE_USERNAME_USER FOREIGN KEY (USERNAME) REFERENCES [USER](USERNAME)
ON UPDATE CASCADE ON DELETE CASCADE


CREATE TRIGGER NGAN_TAO_TAI_KHOAN_MAC_DINH ON [USER] FOR INSERT AS
BEGIN
	DECLARE @USERNAME_INS NVARCHAR(100)

	SET @USERNAME_INS = (SELECT USERNAME FROM INSERTED)

	IF @USERNAME_INS IN ('CEO', 'HR', 'PR')
	BEGIN
		ROLLBACK TRAN;
		PRINT N'VUI LÒNG ĐỔI TÊN ĐĂNG NHẬP'
	END
END


SELECT * FROM [USER] WHERE USERNAME NOT IN ('CEO', 'HR', 'PR')
SELECT * FROM [ROLE] WHERE USERNAME NOT IN ('CEO', 'HR', 'PR')
SELECT R.IDROLE, U.FULLNAME, R.USERNAME, R.ROLECODE, U.IDUSER FROM [USER] U, [ROLE] R 
WHERE U.USERNAME = R.USERNAME AND R.USERNAME NOT IN ('CEO', 'HR', 'PR')
SELECT DISTINCT USERNAME FROM [USER] WHERE USERNAME NOT IN ('CEO', 'HR', 'PR')
SELECT DISTINCT ROLECODE FROM [ROLE] WHERE USERNAME NOT IN ('CEO', 'HR', 'PR')

INSERT INTO [USER](FULLNAME, USERNAME, [PASSWORD]) VALUES(N'Nguyễn Văn A', 'CEO', '1')
INSERT INTO [USER](FULLNAME, USERNAME, [PASSWORD]) VALUES(N'Trần Quang B', 'HR','1')
INSERT INTO [USER](FULLNAME, USERNAME, [PASSWORD]) VALUES(N'Lý Đông C', 'PR', '1')


INSERT INTO [ROLE] VALUES('CEO', 'CEO')
INSERT INTO [ROLE] VALUES('CEO', 'MANAGER_HR')
INSERT INTO [ROLE] VALUES('CEO', 'MANAGER_PR')
INSERT INTO [ROLE] VALUES('HR', 'MANAGER_HR')
INSERT INTO [ROLE] VALUES('PR', 'MANAGER_PR')
